title: Lizzy Lopez
#logo: /img/headshot_circle.png
description: Senior Full Stack Software Engineer

# ğŸ‘‹ Lizzy Lopez

### ğŸ’¼ Senior Full Stack Software Engineer  
ğŸ“ I'm based in Pembroke Pines, FL  

show_downloads: true
theme: jekyll-theme-minimal
